sonar.projectKey=draftmate
sonar.organization=draftmate-org
sonar.projectName=DraftMate
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src,backend

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**,**/migrations/**

# Language
sonar.language=js,py

# Encoding
sonar.sourceEncoding=UTF-8
