apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: draftmate-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: draftmate-frontend
  template:
    metadata:
      labels:
        app: draftmate-frontend
    spec:
      {{- if .Values.affinity.web.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.web.nodeLabelKey }}
                operator: In
                values:
                - {{ .Values.affinity.web.nodeLabelValue | quote }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - draftmate-frontend
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000

      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false # Nginx container needs to write temp files/cache
          capabilities:
            drop:
            - ALL

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        env:
        # Load non-sensitive configs
        {{- range $key, $value := .Values.frontend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        # Load sensitive credentials from Secret
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: draftmate-secrets
              key: {{ $key }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
