{{- range $service := .Values.backend.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ $service.name }}
---
{{- end }}
