apiVersion: v1
kind: Secret
metadata:
  name: draftmate-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # Ensure Secrets are rendered before anything else
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
